name: nlp-beschwerden
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - pandas>=2.0
      - nltk>=3.8
      - spacy>=3.6
      - scikit-learn>=1.3
      - bertopic>=0.14
      - sentence-transformers>=2.2
      - gensim>=4.3
      - matplotlib>=3.8
      - de-core-news-sm @ https://github.com/explosion/spacy-models/releases/download/de_core_news_sm-3.6.0/de_core_news_sm-3.6.0-py3-none-any.whl